### ISSUE TITLE
Definir o root conforme o usuário atual

### ISSUE THREAD

**Issue by ofabriciojr** [nandosousafr/nerd-power-rails#6]
* Se o usuário estiver **logado**: redirecionar para o feed
* Se o usuário estiver **deslogado**: redirecionar para o session#new do Devise

**Comment by ofabriciojr** [comment]
1 ano de issue aberta @nandosousafr :cake: 

:smile:

**Comment by nandosousafr** [comment]
hahahaha nossa,  dia 16 trago :cake: para comemorar oficialmente :_
