### ISSUE TITLE
Draft da Rede

### ISSUE THREAD

**Issue by nandosousafr** [nandosousafr/nerd-power-rails#9]
O que acham desse layout?

![screen shot 2015-03-24 at 12 29 23 pm](https://cloud.githubusercontent.com/assets/818744/6805520/31311ba2-d222-11e4-8ed9-adfc31c6ade6.png)

**Comment by rodgerpaulo** [comment]
Alguém tem os prints do sistema atual?

Queria montar um mapa de conexão entre as páginas tudo certinho... não cheguei a utilizar a rede mas estou disposto à ajudar com layout, usabilidade e front-end

**Comment by ofabriciojr** [comment]
@rodgerpaulo Não temos nenhuma tela definida atualmente. Se quiser começar a desenhar algo, seria bem interessante. Pode contar com a minha ajuda e com a do @nandosousafr

**Comment by rodgerpaulo** [comment]
Mas não foi disponibilizado o código fonte original? Quero saber qual o escopo para começar a desenhar as páginas.

O que de funcionalidade e interação atualmente temos na Skynet?

Podemos trazer para vida o que temos hoje com layout novo e algum redesenho de usabilidade para lançarmos o primeiro beta. Depois começamos a coletar opiniões para aplicarmos novas opções de interação.

Enviado do meu iPhone

**Comment by nandosousafr** [comment]
O que acha de começar um do zero @rodgerpaulo? podes tomar como base o mockup que mandei acima em relação as funcionalidades?

**Comment by rodgerpaulo** [comment]
Tranquilo.

Basicamente uma rede social nerd, Like orkut? Com badges, etc...

Inicialmente poderíamos desenhar:

- Home (landing page com login)
- Time Line (home do usuário)
- Perfil (visualizar)
- Configurações

Enviado do meu iPhone

**Comment by nandosousafr** [comment]
@rodgerpaulo, acredito que badges é bastante overrated.

Mais ou menos assim:

- Esquema de seguidores como o __Twitter__;
- Possibilidade de fazer posts com markdown;
- Trocar DM's como o __Twitter__;
- Possiblidade de seguir um Podcast, ouvir e comentar episódios;
- Hashtags
- Caso o usuário coloque hashtag #spoiler ou #spoilerAlert, não aparece o conteúdo do post (somente as hashtags) com uma mensagem 'Esse artigo contém spoiler, clique aqui para mostrar mesmo assim';
- Sistema de Notificações: DM's, menções, novo episódio de Podcast, novos seguidores, etc...
- Post poderá ser compartilhado ou curtido;
- Haver integrações com facebook e twitter.   

O que acha @rodgerpaulo e @ofabriciojr ?

**Comment by ofabriciojr** [comment]
Acredito que é isso @nandosousafr :+1:

**Comment by nandosousafr** [comment]
Essa thread vai ser discutida aqui: https://trello.com/c/VphdVjYx/4-mockup-feed-page
